resorts = [
    'vail',
    'beavercreek',
    'breckenridge',
    'skicb',
    'keystoneresort',
    'parkcitymountain',
    'skiheavenly',
    'northstarcalifornia',
    'kirkwood',
    'stevenspass',
    'mountsunapee',
    'okemo',
    'stowe',
    'huntermtn',
    'mountsnow',
    'attitash',
    'skiwildcat',
    'crotchedmtn',
    'libertymountainresort',
    'skiroundtop',
    'skiwhitetail',
    'jfbb',
    'aftonalps',
    'mtbrighton',
    'wilmotmountain',
    'alpinevalleyresort',
    'bmbw',
    'skimadriver',
    'skisnowcreek',
    'paolipeaks',
    'whistlerblackcomb',
]


def verify_input(input):
    return input in resorts

pretty_name = [
    'Vail',
    'Beaver Creek',
    'Breckenridge',
    'Crested Butte',
    'Keystone',
    'Park City',
    'Heavenly',
    'Northstar',
    'Kirkwood',
    'Steven\'s Pass',
    'Mount Sunapee',
    'Okemo',
    'Stowe',
    'Hunter Mountain',
    'Mount Snow',
    'Attitash',
    'Wildcat',
    'Crotched',
    'Liberty',
    'Roundtop',
    'Whitetail',
    'Jack Frost Big Boulder',
    'Afton Alps',
    'Mt Brighton',
    'Wilmot',
    'Alpine Valley',
    'Boston Mills & Brandywine',
    'Mad River Mountain',
    'Snow Creek',
    'Paoli Peaks',
    'Whistler Blackcomb',
]
